[package]
name = "hyper-server"
version = "0.0.3"
edition = "2018"
authors = []

[[bin]]
name = "hyper-server"
path = "src/main.rs"

[dependencies]
futures = "0.3.12"
hyper = { version = "0.14.15", features = ["full"] }
tokio = {"version"= "1", features=["rt-multi-thread", "macros"]}

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
